# Declares the base image for you your build, pulls the specified version of Ubuntu from Docker Hub if not available locally
# Base image determines the OS, package manager,system libaries, shell and initial filesystem layout
# It's the first layer, all subsequent additions/changes are layered on the top
FROM ubuntu:3.x-slim

# Sets the working directory subsequent instructions and for the container at runtime
WORKDIR /app






